# Generated by Django 4.2 on 2023-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.IntegerField(null=True),
        ),
    ]
