# Generated by Django 4.1.3 on 2023-04-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="ProfileImg/"),
        ),
    ]
