# Generated by Django 4.1.3 on 2023-04-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="contact_book/media/ProfileImg/"
            ),
        ),
    ]
