# Generated by Django 4.2 on 2023-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="contact_book/media"
            ),
        ),
    ]
